name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: arch-latest

    steps:
    - uses: actions/checkout@v4
    - name Install Dependencies
      run: pacman -S mingw-w64-binutils
    - name: Build
      run: sh build.sh
    - name: Run tests
      run: cargo test --verbose
