name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: binutils-mingw-w64-x86-64
    - name: Build
      run: sh build.sh
    - name: Run tests
      run: cargo test --verbose
